#include <stdio.h>

enum {
    WORKINGSET_NODES,
    WORKINGSET_REFAULT_BASE,
    WORKINGSET_REFAULT_ANON = WORKINGSET_REFAULT_BASE,
    WORKINGSET_REFAULT_FILE,
    WORKINGSET_ACTIVATE_BASE,
    WORKINGSET_ACTIVATE_ANON = WORKINGSET_ACTIVATE_BASE,
    WORKINGSET_ACTIVATE_FILE,
    WORKINGSET_RESTORE_BASE,
    WORKINGSET_RESTORE_ANON = 1,
    WORKINGSET_RESTORE_FILE,
    WORKINGSET_NODERECLAIM,
};

#define PRINT(e) printf("%-30s = %d\n", #e, e)

int main ()
{
    PRINT(WORKINGSET_NODES);
    PRINT(WORKINGSET_REFAULT_BASE);
    PRINT(WORKINGSET_REFAULT_ANON);
    PRINT(WORKINGSET_REFAULT_FILE);
    PRINT(WORKINGSET_ACTIVATE_BASE);
    PRINT(WORKINGSET_ACTIVATE_ANON);
    PRINT(WORKINGSET_ACTIVATE_FILE);
    PRINT(WORKINGSET_RESTORE_BASE);
    PRINT(WORKINGSET_RESTORE_ANON);
    PRINT(WORKINGSET_RESTORE_FILE);
    PRINT(WORKINGSET_NODERECLAIM);

}
