
all:
	gcc openat2_test.c -std=c99 helpers.c -o openat2_test.out
	gcc resolve_test.c -std=c99 helpers.c -o resolve_test.out
	gcc rename_attack_test.c -std=c99 helpers.c -o rename_attack_test.out

clean:
	rm -f *.out
