/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCLOGIN_H_RPCGEN
#define _RPCLOGIN_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct userDetails {
	char username[256];
	char password[256];
};
typedef struct userDetails userDetails;

struct userStatus {
	long rescode;
	long usercount;
};
typedef struct userStatus userStatus;

#define RPCLOGIN_PROG 0x23451111
#define RPCLOGIN_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define REGISTERPROCESS 1
extern  userStatus * registerprocess_1(userDetails *, CLIENT *);
extern  userStatus * registerprocess_1_svc(userDetails *, struct svc_req *);
#define LOGINPROCESS 2
extern  userStatus * loginprocess_1(userDetails *, CLIENT *);
extern  userStatus * loginprocess_1_svc(userDetails *, struct svc_req *);
extern int rpclogin_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define REGISTERPROCESS 1
extern  userStatus * registerprocess_1();
extern  userStatus * registerprocess_1_svc();
#define LOGINPROCESS 2
extern  userStatus * loginprocess_1();
extern  userStatus * loginprocess_1_svc();
extern int rpclogin_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_userDetails (XDR *, userDetails*);
extern  bool_t xdr_userStatus (XDR *, userStatus*);

#else /* K&R C */
extern bool_t xdr_userDetails ();
extern bool_t xdr_userStatus ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPCLOGIN_H_RPCGEN */
