/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "rpclogin.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

userStatus *
registerprocess_1(userDetails *argp, CLIENT *clnt)
{
	static userStatus clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, REGISTERPROCESS,
		(xdrproc_t) xdr_userDetails, (caddr_t) argp,
		(xdrproc_t) xdr_userStatus, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

userStatus *
loginprocess_1(userDetails *argp, CLIENT *clnt)
{
	static userStatus clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, LOGINPROCESS,
		(xdrproc_t) xdr_userDetails, (caddr_t) argp,
		(xdrproc_t) xdr_userStatus, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
